yarnPath: .yarn/releases/yarn-safe.cjs

# Use node_modules mode for React Native/Expo compatibility
nodeLinker: node-modules

# Enable workspaces
enableGlobalCache: true

# Ignore engines for sub-packages
enableStrictSsl: true
enableImmutableInstalls: false
