// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    settings: {
      "import/ignore": ["@moruk/", "react-native", "expo-"],
    },
    rules: {
      "import/no-unresolved": ["error", { ignore: ["^@moruk/", "^react-native", "^expo-"] }],
      "import/namespace": "off",
    },
  },
  // Restrict direct usage of libraries that should use @moruk packages (apps only)
  {
    files: ["apps/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@react-native-async-storage/async-storage",
              message:
                "Use @moruk/storage instead. Import: import { storage } from '@moruk/storage'",
            },
            {
              name: "@react-native-community/netinfo",
              message:
                "Use @moruk/info instead. Import: import { getNetworkInfo } from '@moruk/info'",
            },
            {
              name: "expo-application",
              message:
                "Use @moruk/info instead. Import: import { getAppInfo, getSystemInfo } from '@moruk/info'",
            },
            {
              name: "expo-battery",
              message:
                "Use @moruk/info instead. Import: import { getSystemInfo } from '@moruk/info'",
            },
            {
              name: "expo-constants",
              message:
                "Use @moruk/info instead. Import: import { getAppInfo, getSystemInfo } from '@moruk/info'",
            },
            {
              name: "expo-device",
              message:
                "Use @moruk/info instead. Import: import { getDeviceInfo } from '@moruk/info'",
            },
          ],
        },
      ],
    },
  },
  // Ban console.* usage - enforce @moruk/logger
  {
    files: ["apps/**/*.{ts,tsx,js,jsx}", "packages/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "no-console": "error",
    },
  },
  // Exempt logger package from no-console rule
  {
    files: ["packages/logger/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "no-console": "off",
    },
  },
  // Exempt test files and scripts from no-console rule
  {
    files: [
      "**/__tests__/**/*.{ts,tsx,js,jsx}",
      "**/*.test.{ts,tsx,js,jsx}",
      "**/*.spec.{ts,tsx,js,jsx}",
      "**/jest.setup.{ts,tsx,js,jsx}",
      "**/scripts/**/*.{ts,tsx,js,jsx}",
      "**/store-metadata/**/*.{ts,tsx,js,jsx}",
      // Custom logging services that wrap console
      "**/LogService.{ts,tsx,js,jsx}",
      "**/logging/logger.{ts,tsx,js,jsx}",
    ],
    rules: {
      "no-console": "off",
    },
  },
  {
    ignores: [
      // Dependencies
      "**/node_modules/**",

      // Build outputs
      "**/dist/**",
      "**/build/**",
      "**/web-build/**",
      "**/*.jsbundle",

      // Expo
      "**/.expo/**",
      "**/expo-env.d.ts",

      // EAS
      "**/.eas/**",
      "**/eas-build-*/**",

      // Native (generated by Expo)
      "**/ios/**",
      "**/android/**",
      "**/.kotlin/**",

      // Type definitions (auto-generated)
      "**/svg.d.ts",

      // Coverage & test artifacts
      "**/coverage/**",
      "**/reports/**",
      "**/.stryker-tmp/**",
      "**/.stryker-cache/**",

      // Store metadata (JSON files)
      "**/store-metadata/**",
      "**/store.config.json",

      // Fastlane
      "**/fastlane/**",

      // Yarn
      ".yarn/**",
      ".pnp.*",

      // Lock files
      "yarn.lock",
      "package-lock.json",

      // Misc generated/config
      "**/metro.config.js",
      "**/babel.config.js",
      "**/repomix-output.*",
      "docs/.archive/**",
    ],
  },
]);
