module.exports = {
  testTimeout: 30000,
  testEnvironment: "node",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
  globals: {
    __DEV__: true,
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
  },
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@moruk/.*|@testing-library/react-native|expo-tracking-transparency|react-native-google-mobile-ads)",
  ],
  testMatch: [
    "**/src/config/__tests__/**/*.test.(ts|tsx)",
    "**/src/domain/__tests__/**/*.test.(ts|tsx)",
    "**/src/infrastructure/__tests__/**/*.test.(ts|tsx)",
    "**/src/application/__tests__/**/*.test.(ts|tsx)",
    "**/src/features/**/__tests__/**/*.test.(ts|tsx)",
    "**/src/shared/**/__tests__/**/*.test.(ts|tsx)",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@moruk/ai$": "<rootDir>/src/shared/ai",
    "^@moruk/config$": "<rootDir>/src/shared/config",
    "^@moruk/context$": "<rootDir>/src/shared/context",
    "^@moruk/event-tracking$": "<rootDir>/src/shared/event-tracking",
    "^@moruk/firebase$": "<rootDir>/src/shared/firebase",
    "^@moruk/gemini-client$": "<rootDir>/src/shared/gemini-client",
    "^@moruk/hoc$": "<rootDir>/src/shared/hoc",
    "^@moruk/hooks$": "<rootDir>/src/shared/hooks",
    "^@moruk/image$": "<rootDir>/src/shared/image",
    "^@moruk/image-filter$": "<rootDir>/src/shared/image-filter",
    "^@moruk/info$": "<rootDir>/src/shared/info",
    "^@moruk/logger$": "<rootDir>/src/shared/logger",
    "^@moruk/monitoring-client$": "<rootDir>/src/shared/monitoring-client",
    "^@moruk/navigation$": "<rootDir>/src/shared/navigation",
    "^@moruk/perplexity-client$": "<rootDir>/src/shared/perplexity-client",
    "^@moruk/storage$": "<rootDir>/src/shared/storage",
    "^@moruk/ui$": "<rootDir>/src/shared/ui",
    "^expo-tracking-transparency$": "<rootDir>/__mocks__/expo-tracking-transparency.js",
    "^react-native-google-mobile-ads$": "<rootDir>/__mocks__/react-native-google-mobile-ads.js",
  },
  collectCoverageFrom: [
    "src/domain/**/*.{ts,tsx}",
    "src/infrastructure/**/*.{ts,tsx}",
    "src/application/**/*.{ts,tsx}",
    "!src/domain/**/*.d.ts",
    "!src/infrastructure/**/*.d.ts",
    "!src/application/**/*.d.ts",
    "!src/domain/__tests__/**",
    "!src/infrastructure/__tests__/**",
    "!src/application/__tests__/**",
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testPathIgnorePatterns: ["/node_modules/", "/app/"],
};
